steps:
  # Build image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      '${_CI_IMAGE}',
      './streamlit',
    ]

  # Push image on Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      '${_CI_IMAGE}',
    ]

  # Deploy image on Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run',
      'deploy',
      '${_CI_SERVICE_NAME}',
      '--image',
      '${_CI_IMAGE}',
      '--region',
      '${_CI_REGION}',
      '--port',
      '8501',
      '--service-account',
      '${_CI_SERVICE_ACCOUNT_ID}',
      '--allow-unauthenticated',
    ]
    
images:
  - '${_CI_IMAGE}'

options:
  logging: CLOUD_LOGGING_ONLY
