steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'us-central1-docker.pkg.dev/sample-project-460722/sample-project-repository/streamlit-app', './streamlit' ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'us-central1-docker.pkg.dev/sample-project-460722/sample-project-repository/streamlit-app' ]
    
images:
  - 'us-central1-docker.pkg.dev/sample-project-460722/sample-project-repository/streamlit-app'

options:
  logging: CLOUD_LOGGING_ONLY